<a href="https://colab.research.google.com/github/AUMANSH/Data-Science-Projects/blob/main/92200103209_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
#Use the following import convention:
#Creating Arrays
a = np.array([1,2,3])
a



array([1, 2, 3])

In [ ]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
b



array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [ ]:
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],dtype = float)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [ ]:
 np.zeros((3,4)) #Create an array of zeros


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((2,3,4),dtype=np.int16) #Create an array of ones


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [ ]:
d = np.arange(10,25,5) #Create an array of evenly spaced values (step value)
d


array([10, 15, 20])

In [ ]:
np.linspace(0,2,9) #Create an array of evenly spaced values (number of samples)


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
e = np.full((2,2),7) #Create a constant array
e


array([[7, 7],
       [7, 7]])

In [ ]:
f = np.eye(2) #Create a 2X2 identity matrix
f


array([[1., 0.],
       [0., 1.]])

In [ ]:
np.random.random((2,2)) #Create an array with random values


array([[0.34198558, 0.44758218],
       [0.59973006, 0.20223134]])

In [ ]:
 np.empty((3,2)) #Create an empty array

array([[1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309]])

In [ ]:
 np.int64 #Signed 64-bit integer types


numpy.int64

In [ ]:
np.float32 #Standard double-precision floating point

numpy.float32

In [ ]:
complex #Complex numbers represented by 128 floats

complex

In [ ]:
bool #Boolean type storing TRUE and FALSE values

bool

In [ ]:
 object #Python object type


object

In [ ]:
np.string_ #Fixed-length string type


numpy.bytes_

In [ ]:
np.unicode_ #Fixed-length unicode type

numpy.str_

In [ ]:
g=a-b
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [ ]:
 np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [ ]:
 np.info(np.ndarray.dtype)


Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [ ]:
 a.shape #Array dimensions

(3,)

In [ ]:
 len(a) #Length of array


3

In [ ]:
 b.ndim #Number of array dimensions


2

In [ ]:
 e.size #Number of array elements


4

In [ ]:
b.dtype #Data type of array elements


dtype('float64')

In [ ]:
 b.dtype.name #Name of data type


'float64'

In [ ]:
 b.astype(int) #Convert an array to a different type

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a/b #Array arithmetic

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [ ]:
a*b

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [ ]:
 np.multiply(a,b) #Multiplication


array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [ ]:
 np.exp(b) #Exponentiation



array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [ ]:
np.sqrt(b) #Square root


array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [ ]:
np.sin(a) #Print sines of an array


array([0.84147098, 0.90929743, 0.14112001])

In [ ]:
np.cos(b) #Element-wise cosine


array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [ ]:
 np.log(a) #Element-wise natural logarithm


array([0.        , 0.69314718, 1.09861229])

In [ ]:
 e.dot(f) #Dot product

array([[7., 7.],
       [7., 7.]])

In [ ]:
a == b #Element-wise comparison

array([[False,  True,  True],
       [False, False, False]])

In [ ]:
a < 2 #Element-wise comparison

array([ True, False, False])

In [ ]:
np.array_equal(a, b)

False

In [ ]:
a.sum() #Array-wise sum


6

In [ ]:
a.min() #Array-wise minimum value



1

In [ ]:
 b.max(axis=0) #Maximum value of an array row


array([4., 5., 6.])

In [ ]:
b.cumsum(axis=1) #Cumulative sum of the elements


array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [ ]:
a.mean() #Mean


2.0

In [ ]:
np.median(a) #Median


2.0

In [ ]:
np.corrcoef(a) # Correlation coefficient



1.0

In [ ]:
 np.std(b) #Standard deviation

1.5920810978785667

In [ ]:
h =a.view()
h

array([1, 2, 3])

In [ ]:
np.copy(a)

array([1, 2, 3])

In [ ]:
h=a.copy()
h

array([1, 2, 3])

In [ ]:
a.sort()
a

array([1, 2, 3])

In [ ]:
c.sort(axis=1)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [ ]:
i=np.transpose(b)
i

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [ ]:
i.T

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [ ]:
b.ravel()

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [ ]:
g.reshape(2,3)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [ ]:
import numpy as np

# Create a copy of h before resizing
h_copy = h.copy()
h_copy.resize((2, 6), refcheck=False)

print(h_copy)

[[1 2 3 0 0 0]
 [0 0 0 0 0 0]]


In [ ]:
np.append(h,g)

array([ 1. ,  2. ,  3. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

In [ ]:
np.insert(a,1,5)

array([1, 5, 2, 3])

In [ ]:
np.delete(a,[1])

array([1, 3])

In [ ]:
np.concatenate((a,d),axis=0)

array([ 1,  2,  3, 10, 15, 20])

In [ ]:
 np.vstack((a,b))

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [ ]:
 np.r_[e,f]

array([[7., 7.],
       [7., 7.],
       [1., 0.],
       [0., 1.]])

In [ ]:
 np.hstack((e,f))

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [ ]:
np.column_stack((a,d))

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [ ]:
 np.c_[a,d]

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [ ]:
np.hsplit(a,3)

[array([1]), array([2]), array([3])]

In [ ]:
np.vsplit(c,2)

[array([[[1.5, 2. , 3. ],
         [4. , 5. , 6. ]]]),
 array([[[3., 2., 1.],
         [4., 5., 6.]]])]

In [ ]:
a[2]

3

In [ ]:
 b[1,2]

6.0

In [ ]:
 a[0:2]

array([1, 2])

In [ ]:
b[0:2,1]

array([2., 5.])

In [ ]:
 b[:1]

array([[1.5, 2. , 3. ]])

In [ ]:
c[1,...]

array([[3., 2., 1.],
       [4., 5., 6.]])

In [ ]:
 a[ : :-1]

array([3, 2, 1])

In [ ]:
 a[a<2]

array([1])

In [ ]:
b[[1, 0, 1, 0],[0, 1, 2, 0]]

array([4. , 2. , 6. , 1.5])

In [ ]:
 b[[1, 0, 1, 0]][:,[0,1,2,0]]

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

In [ ]:
np.save('my_array', a)

In [ ]:
np.savez('array.npz', a, b)


In [ ]:
 np.load('my_array.npy')

array([1, 2, 3])

In [ ]:
np.loadtxt("myfile.txt")

array([ 5., 10., 15.])

In [ ]:
 np.genfromtxt("myarray.txt", delimiter=',')

array([1., 2., 3.])

In [ ]:
 np.savetxt("myarray.txt", a, delimiter=" ")

text in myarray.txt:
1.000000000000000000e+00
2.000000000000000000e+00
3.000000000000000000e+00
